name: Inform the Python package index about a new DaCe release.

on:
  #push:
    # Only run once a new tag has been created.
    # TODO: Make sure that the tag is passed to the index update workflow.
    #tags:
      #- __gt4py-next-integration_*

  # We need this until this file is not in `main`, without it the web interface will not pick it up.
  #  See https://stackoverflow.com/a/71057825
  pull_request:

  # For some reasons this does not work, so it can not be triggered manually.
  workflow_dispatch:

jobs:
  update-dace:
    runs-on: ubuntu-latest
    steps:
      - name: Inform Index
        shell: bash
        run: |
          INDEX_ORGANIZATION="gridtools"
          INDEX_REPO="python-pkg-index"

          # We are using `github.sha` here to be sure that we transmit an identifier to the index
          #  that can be checked out. Before we used `github.ref_name` but got strange results
          #  with it.
          DEPENDENCY_REF="${{ github.sha }}"
          SOURCE_REPO="dace"
          SOURCE_OWNER="gridtools"

          curl -L -v \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PKG_UPDATE_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${INDEX_ORGANIZATION}/${INDEX_REPO}/dispatches" \
            -d '{"event_type":"update_package_index","client_payload":{"source_repo":"'"${SOURCE_REPO}"'","source_org":"'"${SOURCE_OWNER}"'","dependency_ref":"'"${DEPENDENCY_REF}"'"}}'
